import type { Subject } from '../types/course';

export const subjects: Subject[] = [
  {
    id: 'shell',
    name: 'Shell',
    icon: '🐚',
    desc: '学习 Bash/Shell 命令行操作，掌握文本处理、管道、脚本编写等核心技能',
    color: '#52c41a',
  },
  {
    id: 'go',
    name: 'Go',
    icon: '🐹',
    desc: '学习 Go 语言基础与进阶，涵盖并发编程、接口设计、项目实战',
    color: '#00ADD8',
  },
  {
    id: 'python',
    name: 'Python',
    icon: '🐍',
    desc: '学习 Python 编程基础、数据处理、Web 开发等实用技能',
    color: '#3776AB',
  },
  {
    id: 'java',
    name: 'Java',
    icon: '☕',
    desc: '学习 Java 面向对象编程、集合框架、多线程、Spring 生态',
    color: '#ED8B00',
  },
  {
    id: 'cpp',
    name: 'C++',
    icon: '⚡',
    desc: '学习 C++ 语言特性、内存管理、STL、模板编程等',
    color: '#00599C',
  },
  {
    id: 'rust',
    name: 'Rust',
    icon: '🦀',
    desc: '学习 Rust 所有权系统、生命周期、并发安全、零成本抽象',
    color: '#CE422B',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    icon: '🔷',
    desc: '学习 TypeScript 类型系统、泛型、装饰器、Node.js 后端开发',
    color: '#3178C6',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    icon: '✨',
    desc: '学习 JS 核心概念：闭包、原型链、异步编程、ES6+ 新特性',
    color: '#F7DF1E',
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    icon: '🎯',
    desc: '学习 Kotlin 语法糖、协程、空安全、函数式编程等特性',
    color: '#7F52FF',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    icon: '🗄️',
    desc: '学习 SQL 查询、数据库设计、索引优化、事务等核心知识',
    color: '#4479A1',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    icon: '🐘',
    desc: '学习 PostgreSQL 高级 SQL、窗口函数、JSONB、CTE、性能调优',
    color: '#336791',
  },
  {
    id: 'redis',
    name: 'Redis',
    icon: '🔴',
    desc: '学习 Redis 数据结构、缓存策略、持久化、分布式锁等',
    color: '#DC382D',
  },
  {
    id: 'linux',
    name: 'Linux',
    icon: '🐧',
    desc: '学习 Linux 系统管理、文件权限、进程管理、网络配置',
    color: '#FCC624',
  },
  {
    id: 'git',
    name: 'Git',
    icon: '🌿',
    desc: '学习 Git 版本控制、分支策略、合并冲突解决、工作流',
    color: '#F05032',
  },
  {
    id: 'docker',
    name: 'Docker',
    icon: '🐳',
    desc: '学习 Docker 容器化、Dockerfile 编写、Compose 编排、镜像优化',
    color: '#2496ED',
  },
  {
    id: 'nginx',
    name: 'Nginx',
    icon: '🔧',
    desc: '学习 Nginx 配置、反向代理、负载均衡、HTTPS、性能调优',
    color: '#009639',
  },
  {
    id: 'regex',
    name: '正则表达式',
    icon: '🔍',
    desc: '学习正则表达式语法、贪婪/懒惰匹配、分组捕获、常用模式',
    color: '#8B5CF6',
  },
  {
    id: 'htmlcss',
    name: 'HTML/CSS',
    icon: '🎨',
    desc: '学习 HTML5 语义化、CSS3 布局（Flex/Grid）、响应式设计',
    color: '#E34F26',
  },
  {
    id: 'network',
    name: 'HTTP/网络',
    icon: '🌐',
    desc: '学习 HTTP 协议、TCP/IP、DNS、HTTPS、WebSocket、网络调试',
    color: '#0EA5E9',
  },
  {
    id: 'algorithm',
    name: '数据结构与算法',
    icon: '🧮',
    desc: '学习数组、链表、树、图、排序、搜索、动态规划等核心算法',
    color: '#EC4899',
  },
];
